name: PR Build

on:
  pull_request:
  merge_group:

concurrency:
  group: pr-build-${{github.event.pull_request.number}}
  cancel-in-progress: true

jobs:
  pr-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: 'guidance.clarity.design/.nvmrc'
      - name: Install Dependencies
        working-directory: guidance.clarity.design
        run: npm ci
      - name: Lint
        working-directory: guidance.clarity.design
        run: npm run lint
      - name: Build
        working-directory: guidance.clarity.design
        run: npm run build
      - name: Deploy Preview
        if: ${{github.event.pull_request.number}}
        working-directory: guidance.clarity.design
        run: npx netlify-cli deploy --message="$GITHUB_REF@$GITHUB_SHA" --site clarity-guidance --alias ${{github.event.pull_request.number}}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Find Comment
        if: ${{github.event.pull_request.number}}
        id: find-comment
        uses: peter-evans/find-comment@v1
        with:
          issue-number: ${{github.event.pull_request.number}}
          comment-author: 'github-actions[bot]'
          body-includes: guidance.clarity.design preview
      - name: Comment
        if: ${{github.event.pull_request.number}}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{steps.find-comment.outputs.comment-id}}
          issue-number: ${{github.event.pull_request.number}}
          body: |
            guidance.clarity.design preview: https://${{github.event.pull_request.number}}--clarity-guidance.netlify.app
          edit-mode: replace
